### ISSUE TITLE
skyimager fails to run on Mac OSX.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skybian#12]
**Describe the bug**
Process exits with:
```
Last login: Thu Apr  2 07:50:50 on ttys000
/Users/evanlinjin/Downloads/fyne-cross/bin/darwin-amd64/skyimager-gui ; exit;
➜  ~ /Users/evanlinjin/Downloads/fyne-cross/bin/darwin-amd64/skyimager-gui ; exit;
Unable to create basic Accelerated OpenGL renderer.
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: NSGL: Failed to find a suitable pixel format
GLFW: Please report this bug in the Go package immediately.
panic: FormatUnavailable: NSGL: Failed to find a suitable pixel format

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.2/glfw.acceptError(0xc000127cf0, 0x2, 0x2, 0x0, 0x0)
	/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20181213070059-819e8ce5125f/v3.2/glfw/error.go:177 +0x201
github.com/go-gl/glfw/v3.2/glfw.CreateWindow(0xa, 0xa, 0x45b951a, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20181213070059-819e8ce5125f/v3.2/glfw/window.go:288 +0x1c1
fyne.io/fyne/internal/driver/glfw.(*gLDriver).CreateWindow.func1()
	/go/pkg/mod/fyne.io/fyne@v1.2.3/internal/driver/glfw/window.go:1051 +0xcd
fyne.io/fyne/internal/driver/glfw.runOnMain(0xc0001b86f0)
	/go/pkg/mod/fyne.io/fyne@v1.2.3/internal/driver/glfw/loop.go:41 +0xab
fyne.io/fyne/internal/driver/glfw.(*gLDriver).CreateWindow(0xc0001b8510, 0x45b951a, 0xd, 0x4672920, 0xc0000c6370)
	/go/pkg/mod/fyne.io/fyne@v1.2.3/internal/driver/glfw/window.go:1044 +0xbf
fyne.io/fyne/app.(*fyneApp).NewWindow(0xc0000b4960, 0x45b951a, 0xd, 0x9, 0x466bf60)
	/go/pkg/mod/fyne.io/fyne@v1.2.3/app/app.go:43 +0x47
github.com/SkycoinProject/skybian/pkg/imager.NewFyneGUI(0x4679320, 0xc000099eb0, 0x46663e0, 0xc000099ef0, 0x0)
	/app/pkg/imager/fyne.go:59 +0x1cb
main.main()
	/app/cmd/skyimager-gui/skyimager-gui.go:65 +0x1e2

[Process completed]
```

**Environment information:**

- OS: Mac OS X
- Platform: Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Steps to Reproduce**
Run `skyimager`

**Comment by jdknives** [comment]
Cannot reproduce it anymore. Am on the same version.
