### ISSUE TITLE
Segfault on skywire-cli visor gen-config 

### ISSUE THREAD

**Issue by tanevanwifferen** [skycoin/skybian#92]
**Describe the bug**
The skywire-cli executable doesn't run after update

**Environment information:**

- OS: Skybian on official skyminer
- Platform: Linux 5.10.16-sunxi64 #21.02.2 SMP Sun Feb 14 21:17:31 CET 2021 aarch64

**Steps to Reproduce**

1. Update node
2. verify #91 appears
3. try `skywire-cli visor gen-config -o /etc/skywire-visor.json`
4. output is segfault, stacktrace in additional info

**Actual behavior**
skywire-cli segfaults 

**Expected behavior**
A new config file should be created

**Additional context**
Stacktrace can be one of the following, the choice is random:

```
fatal error: slice bounds out of range

runtime stack:
runtime.throw(0x605a39, 0x19)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:1116 +0x54
runtime.panicCheck1(0x5e690, 0x605a39, 0x19)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:34 +0xc4
runtime.goPanicSliceB(0x6d0694, 0x38fde3)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:115 +0x3c
runtime.pcvalue(0x8acd98, 0xacf240, 0xffff006d0694, 0x1f099c, 0xfffffea49400, 0xacf201, 0xfffffea492b8)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/symtab.go:738 +0x470
runtime.funcspdelta(0x8acd98, 0xacf240, 0x1f099c, 0xfffffea49400, 0xffff00000030)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/symtab.go:844 +0x50
runtime.gentraceback(0x3a0bc, 0x400006aa10, 0x0, 0x4000000180, 0x0, 0x400006aa68, 0x20, 0x0, 0x0, 0x0, ...)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/traceback.go:220 +0x10f4
runtime.callers.func1()
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/traceback.go:804 +0x6c
runtime.systemstack(0xc389a0)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/asm_arm64.s:237 +0xa0
runtime.mstart()
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/proc.go:1041

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/asm_arm64.s:182 +0x8 fp=0x400006a9a0 sp=0x400006a990 pc=0x6d4c8
runtime.callers(0x4, 0x400006aa68, 0x20, 0x20, 0xffff8d0f7fff)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/traceback.go:803 +0x88 fp=0x400006aa10 sp=0x400006a9a0 pc=0x65898
runtime.mProf_Malloc(0x400011b800, 0x80)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/mprof.go:342 +0x5c fp=0x400006ab90 sp=0x400006aa10 pc=0x3a0bc
runtime.profilealloc(0xc39140, 0x400011b800, 0x80)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/malloc.go:1197 +0x54 fp=0x400006abb0 sp=0x400006ab90 pc=0x1bf84
runtime.mallocgc(0x80, 0x5adda0, 0x571001, 0x400011b780)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/malloc.go:1116 +0x3dc fp=0x400006ac70 sp=0x400006abb0 pc=0x1b6bc
runtime.newobject(0x5adda0, 0x400006add8)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/malloc.go:1165 +0x38 fp=0x400006aca0 sp=0x400006ac70 pc=0x1bcf8
fatal error: slice bounds out of range
panic during panic

runtime stack:
runtime.throw(0x605a39, 0x19)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:1116 +0x54
runtime.panicCheck1(0x5e690, 0x605a39, 0x19)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:34 +0xc4
runtime.goPanicSliceB(0x6d0694, 0x38fde3)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:115 +0x3c
runtime.pcvalue(0x8acd98, 0xacf240, 0x6d0694, 0x1f099c, 0xfffffea48ba0, 0x42101, 0x1)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/symtab.go:738 +0x470
runtime.funcspdelta(0x8acd98, 0xacf240, 0x1f099c, 0xfffffea48ba0, 0x3b)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/symtab.go:844 +0x50
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0x4000000180, 0x0, 0x0, 0x64, 0x0, 0x0, 0x0, ...)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/traceback.go:220 +0x10f4
runtime.traceback1(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0x4000000180, 0x0)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/traceback.go:736 +0xc4
runtime.traceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0x4000000180)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/traceback.go:690 +0x44
runtime.tracebackothers(0xc389a0)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/traceback.go:926 +0x258
runtime.dopanic_m(0xc389a0, 0x40a14, 0xfffffea490f0, 0x42114)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:1322 +0x2c0
runtime.fatalthrow.func1()
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:1171 +0x54
runtime.fatalthrow()
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:1168 +0x40
runtime.throw(0x605a39, 0x19)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:1116 +0x54
runtime.panicCheck1(0x5e690, 0x605a39, 0x19)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:34 +0xc4
runtime.goPanicSliceB(0x6d0694, 0x38fde3)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:115 +0x3c
runtime.pcvalue(0x8acd98, 0xacf240, 0xffff006d0694, 0x1f099c, 0xfffffea49400, 0xacf201, 0xfffffea492b8)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/symtab.go:738 +0x470
runtime.funcspdelta(0x8acd98, 0xacf240, 0x1f099c, 0xfffffea49400, 0xffff00000030)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/symtab.go:844 +0x50
runtime.gentraceback(0x3a0bc, 0x400006aa10, 0x0, 0x4000000180, 0x0, 0x400006aa68, 0x20, 0x0, 0x0, 0x0, ...)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/traceback.go:220 +0x10f4
runtime.callers.func1()
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/traceback.go:804 +0x6c
runtime.systemstack(0xc389a0)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/asm_arm64.s:237 +0xa0
runtime.mstart()
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/proc.go:1041
```

```
invalid spdelta ntime.(*mheap).tryAllocMSpan 0x1dfc800049be8 0x1c043c 0x1e050 4575
runtime: frame ntime.(*mheap).tryAllocMSpan untyped locals 0x400008d380+0x11d7
fatal error: missing stackmap

runtime stack:
runtime.throw(0x5ff409, 0x10)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:1116 +0x54
runtime.getStackMap(0xffffdb1f7d60, 0xffffdb1f7e70, 0x1, 0x1, 0xffffdb1f7a18, 0x5eb44, 0xc64280, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/stack.go:1239 +0x6d8
runtime.adjustframe(0xffffdb1f7d60, 0xffffdb1f7e58, 0xacf240)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/stack.go:636 +0x64
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0x4000000180, 0x0, 0x0, 0x7fffffff, 0x626118, 0xffffdb1f7e58, 0x0, ...)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/traceback.go:334 +0xd78
runtime.copystack(0x4000000180, 0x2000)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/stack.go:888 +0x1fc
runtime.newstack()
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/stack.go:1043 +0x19c
runtime.morestack()
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/asm_arm64.s:310 +0x70

goroutine 1 [copystack, locked to thread]:
runtime.makeslice(0x514dc0, 0x4, 0x8, 0x0)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/slice.go:34 +0x150 fp=0x400008d380 sp=0x400008d380 pc=0x58440
invalid spdelta ntime.(*mheap).tryAllocMSpan 0x1dfc800049be8 0x1c043c 0x1e050 4575
ntime.(*mheap).tryAllocMSpan(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        ?:0 fp=0x400008e55f sp=0x400008d380 pc=0x1c043c
invalid spdelta  0x18828000236d4 0x1bf16c 0x188a4 -1
runtime: unexpected return pc for  called from 0x0
stack: frame={sp:0x400008e55f, fp:0x400008e55e} stack=[0x400008c000,0x400008e000)

(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/type.go:39 fp=0x400008e55e sp=0x400008e55f pc=0x1bf16c 
```

**Possible implementation**
No idea..

**Comment by jdknives** [comment]
@tanevanwifferen thanks for this one as well. Will fix this case.

**Comment by mrpalide** [comment]
No error appear in test on latest commit of skybian@develop.
